// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['gui']['ScannerService']['CancelDownload']();
}

export function CheckForUpdates() {
  return window['go']['gui']['ScannerService']['CheckForUpdates']();
}

export function Clean(arg1, arg2) {
  return window['go']['gui']['ScannerService']['Clean'](arg1, arg2);
}

export function DownloadUpdate() {
  return window['go']['gui']['ScannerService']['DownloadUpdate']();
}

export function GetDownloadProgress() {
  return window['go']['gui']['ScannerService']['GetDownloadProgress']();
}

export function GetLanguage() {
  return window['go']['gui']['ScannerService']['GetLanguage']();
}

export function GetLastResult() {
  return window['go']['gui']['ScannerService']['GetLastResult']();
}

export function GetReminderConfig() {
  return window['go']['gui']['ScannerService']['GetReminderConfig']();
}

export function GetTopGrowers() {
  return window['go']['gui']['ScannerService']['GetTopGrowers']();
}

export function GetTranslations(arg1) {
  return window['go']['gui']['ScannerService']['GetTranslations'](arg1);
}

export function GetTrashConfig() {
  return window['go']['gui']['ScannerService']['GetTrashConfig']();
}

export function GetTrends(arg1) {
  return window['go']['gui']['ScannerService']['GetTrends'](arg1);
}

export function GetUninstallStatus() {
  return window['go']['gui']['ScannerService']['GetUninstallStatus']();
}

export function GetUpdateConfig() {
  return window['go']['gui']['ScannerService']['GetUpdateConfig']();
}

export function GetUpdateStatus() {
  return window['go']['gui']['ScannerService']['GetUpdateStatus']();
}

export function GetVersion() {
  return window['go']['gui']['ScannerService']['GetVersion']();
}

export function IgnoreVersion(arg1) {
  return window['go']['gui']['ScannerService']['IgnoreVersion'](arg1);
}

export function InstallUpdate() {
  return window['go']['gui']['ScannerService']['InstallUpdate']();
}

export function OpenURL(arg1) {
  return window['go']['gui']['ScannerService']['OpenURL'](arg1);
}

export function OrphanTrash(arg1) {
  return window['go']['gui']['ScannerService']['OrphanTrash'](arg1);
}

export function PurgeNow(arg1) {
  return window['go']['gui']['ScannerService']['PurgeNow'](arg1);
}

export function Restore(arg1) {
  return window['go']['gui']['ScannerService']['Restore'](arg1);
}

export function Scan() {
  return window['go']['gui']['ScannerService']['Scan']();
}

export function ScanIfChanged() {
  return window['go']['gui']['ScannerService']['ScanIfChanged']();
}

export function SetLanguage(arg1) {
  return window['go']['gui']['ScannerService']['SetLanguage'](arg1);
}

export function SetLanguagePreference(arg1) {
  return window['go']['gui']['ScannerService']['SetLanguagePreference'](arg1);
}

export function SetReminderConfig(arg1) {
  return window['go']['gui']['ScannerService']['SetReminderConfig'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['gui']['ScannerService']['SetTheme'](arg1);
}

export function SetTrashConfig(arg1) {
  return window['go']['gui']['ScannerService']['SetTrashConfig'](arg1);
}

export function SetUpdateConfig(arg1) {
  return window['go']['gui']['ScannerService']['SetUpdateConfig'](arg1);
}

export function Startup(arg1) {
  return window['go']['gui']['ScannerService']['Startup'](arg1);
}

export function TrashInfo() {
  return window['go']['gui']['ScannerService']['TrashInfo']();
}

export function TrashList() {
  return window['go']['gui']['ScannerService']['TrashList']();
}

export function UninstallBlocked(arg1) {
  return window['go']['gui']['ScannerService']['UninstallBlocked'](arg1);
}

export function UninstallDeleteResidues(arg1) {
  return window['go']['gui']['ScannerService']['UninstallDeleteResidues'](arg1);
}

export function UninstallResidue() {
  return window['go']['gui']['ScannerService']['UninstallResidue']();
}

export function UninstallRunOfficial() {
  return window['go']['gui']['ScannerService']['UninstallRunOfficial']();
}

export function UninstallStart(arg1) {
  return window['go']['gui']['ScannerService']['UninstallStart'](arg1);
}

export function UninstallTrashResidues(arg1) {
  return window['go']['gui']['ScannerService']['UninstallTrashResidues'](arg1);
}
