// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CancelDownload():Promise<string>;

export function CheckForUpdates():Promise<string>;

export function Clean(arg1:Array<string>,arg2:boolean):Promise<string>;

export function DownloadUpdate():Promise<string>;

export function GetDownloadProgress():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLastResult():Promise<string>;

export function GetReminderConfig():Promise<string>;

export function GetTopGrowers():Promise<string>;

export function GetTranslations(arg1:string):Promise<string>;

export function GetTrashConfig():Promise<string>;

export function GetTrends(arg1:number):Promise<string>;

export function GetUninstallStatus():Promise<string>;

export function GetUpdateConfig():Promise<string>;

export function GetUpdateStatus():Promise<string>;

export function GetVersion():Promise<string>;

export function IgnoreVersion(arg1:string):Promise<string>;

export function InstallUpdate():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function PurgeNow(arg1:Array<string>):Promise<string>;

export function Restore(arg1:string):Promise<string>;

export function Scan():Promise<void>;

export function SetLanguage(arg1:string):Promise<string>;

export function SetLanguagePreference(arg1:string):Promise<string>;

export function SetReminderConfig(arg1:string):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function SetTrashConfig(arg1:string):Promise<string>;

export function SetUpdateConfig(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function TrashInfo():Promise<string>;

export function TrashList():Promise<string>;

export function UninstallResidue():Promise<string>;

export function UninstallRunOfficial():Promise<string>;

export function UninstallStart(arg1:string):Promise<string>;

export function UninstallTrashResidues(arg1:Array<string>):Promise<string>;
