// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Clean(arg1:Array<string>,arg2:boolean):Promise<string>;

export function GetLastResult():Promise<string>;

export function GetVersion():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Scan():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
