// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Clean(arg1:Array<string>,arg2:boolean):Promise<string>;

export function GetLastResult():Promise<string>;

export function GetReminderConfig():Promise<string>;

export function GetTopGrowers():Promise<string>;

export function GetTrashConfig():Promise<string>;

export function GetTrends(arg1:number):Promise<string>;

export function GetVersion():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function PurgeNow(arg1:Array<string>):Promise<string>;

export function Restore(arg1:string):Promise<string>;

export function Scan():Promise<void>;

export function SetReminderConfig(arg1:string):Promise<string>;

export function SetTrashConfig(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function TrashInfo():Promise<string>;

export function TrashList():Promise<string>;
