// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean(arg1, arg2) {
  return window['go']['gui']['ScannerService']['Clean'](arg1, arg2);
}

export function GetLastResult() {
  return window['go']['gui']['ScannerService']['GetLastResult']();
}

export function GetReminderConfig() {
  return window['go']['gui']['ScannerService']['GetReminderConfig']();
}

export function GetTopGrowers() {
  return window['go']['gui']['ScannerService']['GetTopGrowers']();
}

export function GetTrashConfig() {
  return window['go']['gui']['ScannerService']['GetTrashConfig']();
}

export function GetTrends(arg1) {
  return window['go']['gui']['ScannerService']['GetTrends'](arg1);
}

export function GetVersion() {
  return window['go']['gui']['ScannerService']['GetVersion']();
}

export function OpenURL(arg1) {
  return window['go']['gui']['ScannerService']['OpenURL'](arg1);
}

export function PurgeNow(arg1) {
  return window['go']['gui']['ScannerService']['PurgeNow'](arg1);
}

export function Restore(arg1) {
  return window['go']['gui']['ScannerService']['Restore'](arg1);
}

export function Scan() {
  return window['go']['gui']['ScannerService']['Scan']();
}

export function SetReminderConfig(arg1) {
  return window['go']['gui']['ScannerService']['SetReminderConfig'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['gui']['ScannerService']['SetTheme'](arg1);
}

export function SetTrashConfig(arg1) {
  return window['go']['gui']['ScannerService']['SetTrashConfig'](arg1);
}

export function Startup(arg1) {
  return window['go']['gui']['ScannerService']['Startup'](arg1);
}

export function TrashInfo() {
  return window['go']['gui']['ScannerService']['TrashInfo']();
}

export function TrashList() {
  return window['go']['gui']['ScannerService']['TrashList']();
}
